name: Ruby

on: push

jobs:
  test:
    name: "Tests (on Ruby ${{ matrix.ruby_version }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby_version: [2.5, 2.6, 2.7, 3.0, 3.1, 3.2, 3.3]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby_version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true
        bundler: latest
    - name: Run tests
      run: bin/rake test

  lint:
    name: "Lint (using Rubocop)"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Lint Ruby code
      run: bin/rubocop
